C2TZX=../../src/c2tzx
TZX_HEADER=../../share/header.bin
CC=sdcc
CFLAGS=-mz80 --no-std-crt0 --code-loc 32768 --xram-loc 50000
PROG=test

all: ${PROG}.tzx

${PROG}.ihx: ${PROG}.c
	sdcc ${CFLAGS} ${PROG}.c

${PROG}.bin: ${PROG}.ihx
	objcopy -I ihex -O binary ${PROG}.ihx ${PROG}.bin

${PROG}.tzx: ${PROG}.bin
	${C2TZX} ${TZX_HEADER} ${PROG}.bin ${PROG}.tzx

CLEAN_EXTS=bin ihx tzx lstlnk o sym lst map lnk asm
clean:
.for i in ${CLEAN_EXTS}
	rm -f ${PROG}.${i}
.endfor
